server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      example:
        test:
          domain:
            board:
              controller: DEBUG
              service: DEBUG