CREATE TABLE BOARD_DEF
(
    BOARD_CD VARCHAR(255),
    BOARD_NM VARCHAR(255)
);
ALTER TABLE BOARD_DEF
    ADD CONSTRAINT pk_board_code PRIMARY KEY (BOARD_CD);

INSERT INTO BOARD_DEF (BOARD_CD, BOARD_NM) values ('00001', 'board');

CREATE TABLE POST
(
    POST_NO   INT,
    BOARD_CD  VARCHAR(10),
    POST_SJ   VARCHAR(50),
    POST_CN   VARCHAR(1000),
    REGSTR_ID VARCHAR(10),
    REG_DT    DATETIME
);
ALTER TABLE POST
    ADD CONSTRAINT pk_post_index PRIMARY KEY (POST_NO);

ALTER TABLE POST
    ADD CONSTRAINT fk_board_cd
        FOREIGN KEY (BOARD_CD)
            REFERENCES BOARD_DEF (BOARD_CD);


CREATE TABLE TAG
(
    TAG_NO   INT,
    TAG      VARCHAR(10),
    BOARD_CD VARCHAR(10)
);


CREATE TABLE POST_TAG
(
    BOARD_TAG_ID INT,
    POST_NO      INT,
    BOARD_CD     VARCHAR(10),
    TAG_NO       INT
);